### PR TITLE
FIRM28: Repository refactoring and improvements

### PR DESCRIPTION
**Pull request by brunofalmeida**
This branch ended up having a lot more changes than I originally planned, but I thought of most of these changes as I was working so it would have been difficult to separate them onto different branches.

Repository organization/structure:
- Rename `Src/drivers` to `Src/common/stm32`, reorganize and make folder naming more consistent
- Reorganize separate "clock" files for different MCU models into the same folder, rename to "init" files with a common header file
- Reorganize `Drivers` with subfolders for MCU series and a common subfolder
- Rename `Startup` to `System` and move to subfolders under `Drivers`
- Combine duplicated `System` files into common files shared between MCU series
- Remove unused `syscalls.c` file
- Remove unused linker scripts
- Create folders under `Src` and `Manual_Tests` for each board/subsystem (currently just dev kits)
- Refactor all MCU I/O and configuration information into a single header file for each board
- Add `*.launch`, `Drivers`, and `Core` (generated IDE files) to `.gitignore`

IDE projects and CMake build:
- Update settings for reorganized folders
- Define `USE_FULL_ASSERT` macro
- Enable `-u_printf_float` and `-u_scanf_float` flags
- Enable additional warnings and flags

IDE projects:
- Simplify `*.ioc` files to only enable the bare minimum of features - this simplifies the future process of enabling a peripheral, generating code, and finding/copying the necessary code to work with that specific peripheral

CMake build:
- Refactor compiler and linker settings
- Only compile source files and manual tests that are intended to work on the specified MCU model

Makefile:
- Only auto-detect MCUs if `DETECT=1` to prevent always resetting connected MCUs

Codebase:
- Fix all TODOs
- Fix uses of MCU series and model macros
- Clean up `#include` statements
- Miscellaneous fixes for warnings and potential bugs
- Consistency improvements
- Update conventions, style, and formatting to match our firmware design guidelines (indentation, line width, asterisk placement, folder/file naming)

MCU library:
- Add `HAL.h` as a common file that includes the correct HAL
- Clean up HAL configurations, disable unused modules
- Throw a preprocessor error if the macros defined for MCU series and model are invalid
- Update G474 and H743 MCU init code for max performance settings
- Refactor basic MCU initialization to reduce code duplication
- Create `MCU` struct and library to simplify MCU and HAL initialization
- Create enums for MCU board, model, device ID
- Add detection of 96-bit MCU UID (unique ID), auto detection of board based on UID
- Initialize peripherals with a pointer to an `MCU` struct
- Add a global default `MCU` struct pointer
- Throw errors for Cortex exceptions (e.g. hard fault, memory management fault, bus fault)

GPIO library:
- Separate code into multiple files (by GPIO type)
- Add common `GPIO.h` file to include all GPIO header files
- Fix struct naming for consistency
- Make existing functions more consistent, add necessary parameters
- Add useful functions (e.g. is state, wait for state)
- Add interrupt input library

UART library:
- Refactor initialization
- Add LPUART1 support
- Change default baud from 115,200 to 230,400
- Add change baud function
- Refactor input functions
- Add double input function
- Add wait for key press function
- Remove RX timeout
- Update input functions to output a configurable prompt before reading input
- Refactor TX wait for ready
- Refactor DMA write to copy data to UART buffer before starting DMA

Log library:
- Refactor logging implementation
- Add functions for logging byte arrays (`uint8_t*`)

Utilities library:
- Add new utilities (`util`) library
- Move existing utility functions into `util` library
- Add functions for bit masks, bit extraction, serialization, deserialization, etc.

Random library:
- Add RNG HAL files
- Add random number generation library
- Seed by default with the MCU's RNG peripheral (true random)
- Can manually set the seed to reproduce a sequence of random numbers

### CODE REVIEW

**Comment by brunofalmeida** [comment]
@cam-rod All done, tested, and ready to merge, although I realize there are a ton of changes for you to review here.

**Review by cam-rod — CHANGES_REQUESTED** [review]
Hey Bruno, only thing I saw was to add a introductory comment to the `*Test.c` files you created, and  a sentence on the type of functions in [Util.c](Src/common/stm32/util/Util.c) and other driver files. Otherwise this is amazing, thank you!

**Comment by brunofalmeida** [comment]
All tested and working!

**Review by cam-rod — APPROVED** [review]
Thanks for the refactor, merging this in!

**Pull request merged**
